# 1. Kích ho?t h? t?ng AndroidX th? h? m?i
android.useAndroidX=true
android.enableJetifier=true

# 2. T?T TUY?T ??I CÁC TÍNH N?NG T?I ?U HÓA GÂY XUNG ??T PHIÊN B?N (QUAN TR?NG)
org.gradle.configuration-cache=false
org.gradle.unsafe.isolated-projects=false

# 3. ÉP GRADLE CH?Y ? CH? ?? GI?M T?I NGHIÊM NG?T
org.gradle.configureondemand=false
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false